source 'https://rubygems.org'

gem 'net-http', '~> 0.9.1'

gem 'fileutils', '~> 1.8'

gem "json", "~> 2.19"

gem "rspec", "~> 3.13"

gem "tempfile", "~> 0.3.1"

gem "net-http-digest_auth", "~> 1.4"

gem "net-imap", "~> 0.5"
